//+------------------------------------------------------------------+
//|                                              JournalBridge.mq5   |
//|  DATA BRIDGE ONLY. Contains no OrderSend / PositionOpen /        |
//|  PositionClose / OrderModify or any trading function.            |
//|  Reads account + position + deal history and POSTs it to the     |
//|  journal API. Syncs BOTH open positions and closed trades.       |
//+------------------------------------------------------------------+
#property copyright   "Trading Journal Bridge"
#property version     "1.10"
#property strict

input string InpJournalApiUrl   = "https://your-journal-domain.example.com/api/mt5/bridge/sync";
input string InpBridgeToken     = "";     // paste the token generated by the journal
input int    InpSyncIntervalSec = 45;     // 30-60s per spec

datetime g_lastSync = 0;
datetime g_lastHistoryTo = 0;

int OnInit()
  {
   if(StringLen(InpBridgeToken) == 0)
     {
      Print("JournalBridge: no bridge token set — refusing to start.");
      return(INIT_PARAMETERS_INCORRECT);
     }
   EventSetTimer(InpSyncIntervalSec);
   Print("JournalBridge: started. Data bridge only — no trading permissions used.");
   return(INIT_SUCCEEDED);
  }

void OnDeinit(const int reason)
  {
   EventKillTimer();
  }

void OnTimer()
  {
   SyncToJournal();
  }

string TimeToIsoStringUtc(datetime serverTime)
  {
   datetime utc = serverTime - TimeGMTOffset();
   return TimeToString(utc, TIME_DATE) + "T" + TimeToString(utc, TIME_SECONDS) + "Z";
  }

string ContractSizeJson(string symbol)
  {
   double cs = SymbolInfoDouble(symbol, SYMBOL_TRADE_CONTRACT_SIZE);
   if(cs <= 0.0) return "null";
   return DoubleToString(cs, 2);
  }

string NumOrNull(double v, bool have, int digits)
  {
   if(!have) return "null";
   return DoubleToString(v, digits);
  }

string BuildOpenPositionsJson()
  {
   string out = "";
   bool first = true;
   int total = PositionsTotal();

   for(int i = 0; i < total; i++)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;

      string symbol   = PositionGetString(POSITION_SYMBOL);
      long   ptype     = PositionGetInteger(POSITION_TYPE);
      string side      = (ptype == POSITION_TYPE_SELL) ? "SELL" : "BUY";
      double volume    = PositionGetDouble(POSITION_VOLUME);
      double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      double sl        = PositionGetDouble(POSITION_SL);
      double tp        = PositionGetDouble(POSITION_TP);
      double profit    = PositionGetDouble(POSITION_PROFIT);
      double swap      = PositionGetDouble(POSITION_SWAP);
      datetime otime   = (datetime)PositionGetInteger(POSITION_TIME);
      long positionId  = PositionGetInteger(POSITION_IDENTIFIER);

      if(!first) out += ",";
      first = false;

      out += StringFormat(
         "{\"positionId\":\"%I64u\",\"openDealId\":null,\"closeDealId\":null,\"status\":\"OPEN\","
         "\"symbol\":\"%s\",\"side\":\"%s\",\"volume\":%f,"
         "\"entryPrice\":%f,\"exitPrice\":null,"
         "\"stopLoss\":%s,\"takeProfit\":%s,"
         "\"profit\":%f,\"commission\":null,\"swap\":%f,"
         "\"entryAt\":\"%s\",\"exitAt\":null,"
         "\"equityBeforeTrade\":null,\"contractSize\":%s,\"hasJournalSetupGrade\":null}",
         positionId, symbol, side, volume,
         openPrice,
         NumOrNull(sl, sl > 0.0, _Digits), NumOrNull(tp, tp > 0.0, _Digits),
         profit, swap,
         TimeToIsoStringUtc(otime),
         ContractSizeJson(symbol)
      );
     }

   return out;
  }

string BuildClosedTradesJson()
  {
   string out = "";
   bool first = true;
   HistorySelect(g_lastHistoryTo, TimeCurrent());
   int total = HistoryDealsTotal();

   ulong ticketsDesc[];
   int n = 0;
   ArrayResize(ticketsDesc, total);
   for(int i = total - 1; i >= 0; i--)
     {
      ulong t = HistoryDealGetTicket(i);
      if(t == 0) continue;
      if(HistoryDealGetInteger(t, DEAL_ENTRY) != DEAL_ENTRY_OUT) continue;
      ticketsDesc[n++] = t;
     }
   for(int a = 0; a < n - 1; a++)
     for(int b = a + 1; b < n; b++)
       if(HistoryDealGetInteger(ticketsDesc[a], DEAL_TIME) < HistoryDealGetInteger(ticketsDesc[b], DEAL_TIME))
         { ulong tmp = ticketsDesc[a]; ticketsDesc[a] = ticketsDesc[b]; ticketsDesc[b] = tmp; }

   double equityBefore[];
   ArrayResize(equityBefore, n);
   double runningBalance = AccountInfoDouble(ACCOUNT_BALANCE);
   for(int k = 0; k < n; k++)
     {
      ulong t = ticketsDesc[k];
      double net = HistoryDealGetDouble(t, DEAL_PROFIT) + HistoryDealGetDouble(t, DEAL_COMMISSION) + HistoryDealGetDouble(t, DEAL_SWAP);
      equityBefore[k] = runningBalance - net;
      runningBalance -= net;
     }

   for(int k = n - 1; k >= 0; k--) // emit oldest -> newest
     {
      ulong ticket = ticketsDesc[k];

      string symbol   = HistoryDealGetString(ticket, DEAL_SYMBOL);
      long   dtype     = HistoryDealGetInteger(ticket, DEAL_TYPE);
      string side      = (dtype == DEAL_TYPE_SELL) ? "SELL" : "BUY";
      double volume    = HistoryDealGetDouble(ticket, DEAL_VOLUME);
      double price     = HistoryDealGetDouble(ticket, DEAL_PRICE);
      double profit    = HistoryDealGetDouble(ticket, DEAL_PROFIT);
      double commission= HistoryDealGetDouble(ticket, DEAL_COMMISSION);
      double swap      = HistoryDealGetDouble(ticket, DEAL_SWAP);
      datetime dtime   = (datetime)HistoryDealGetInteger(ticket, DEAL_TIME);
      long positionId  = HistoryDealGetInteger(ticket, DEAL_POSITION_ID);

      double stopLoss = 0.0;
      bool haveSl = false;
      ulong openDealTicket = 0;

      if(HistorySelectByPosition(positionId))
        {
         int ordersInPos = HistoryOrdersTotal();
         for(int oi = 0; oi < ordersInPos; oi++)
           {
            ulong oticket = HistoryOrderGetTicket(oi);
            if(oticket == 0) continue;
            double sl = HistoryOrderGetDouble(oticket, ORDER_SL);
            if(sl > 0.0) { stopLoss = sl; haveSl = true; break; }
           }

         int dealsInPos = HistoryDealsTotal();
         for(int di = 0; di < dealsInPos; di++)
           {
            ulong dticket = HistoryDealGetTicket(di);
            if(dticket == 0) continue;
            if(HistoryDealGetInteger(dticket, DEAL_ENTRY) == DEAL_ENTRY_IN)
              { openDealTicket = dticket; break; }
           }
         HistorySelect(g_lastHistoryTo, TimeCurrent());
        }

      string entryIso = TimeToIsoStringUtc(dtime);

      if(!first) out += ",";
      first = false;

      out += StringFormat(
         "{\"positionId\":\"%I64u\",\"openDealId\":%s,\"closeDealId\":\"%I64u\",\"status\":\"CLOSED\","
         "\"symbol\":\"%s\",\"side\":\"%s\",\"volume\":%f,"
         "\"entryPrice\":%f,\"exitPrice\":%f,"
         "\"stopLoss\":%s,\"takeProfit\":null,"
         "\"profit\":%f,\"commission\":%f,\"swap\":%f,"
         "\"entryAt\":\"%s\",\"exitAt\":\"%s\","
         "\"equityBeforeTrade\":%f,\"contractSize\":%s,\"hasJournalSetupGrade\":null}",
         positionId,
         (openDealTicket > 0 ? ("\"" + IntegerToString(openDealTicket) + "\"") : "null"),
         ticket,
         symbol, side, volume,
         price, price,
         (haveSl ? DoubleToString(stopLoss, _Digits) : "null"),
         profit, commission, swap,
         entryIso, entryIso,
         equityBefore[k],
         ContractSizeJson(symbol)
      );
     }

   g_lastHistoryTo = TimeCurrent();
   return out;
  }

void SyncToJournal()
  {
   string openJson = BuildOpenPositionsJson();
   string closedJson = BuildClosedTradesJson();

   string trades = openJson;
   if(StringLen(openJson) > 0 && StringLen(closedJson) > 0) trades += ",";
   trades += closedJson;

   string payload = StringFormat(
      "{\"bridgeToken\":\"%s\",\"broker\":\"%s\",\"server\":\"%s\",\"accountNumber\":\"%I64u\","
      "\"balance\":%f,\"equity\":%f,\"freeMargin\":%f,\"margin\":%f,\"currency\":\"%s\","
      "\"bridgeVersion\":\"1.10\",\"trades\":[%s]}",
      InpBridgeToken,
      AccountInfoString(ACCOUNT_COMPANY),
      AccountInfoString(ACCOUNT_SERVER),
      AccountInfoInteger(ACCOUNT_LOGIN),
      AccountInfoDouble(ACCOUNT_BALANCE),
      AccountInfoDouble(ACCOUNT_EQUITY),
      AccountInfoDouble(ACCOUNT_MARGIN_FREE),
      AccountInfoDouble(ACCOUNT_MARGIN),
      AccountInfoString(ACCOUNT_CURRENCY),
      trades
   );

   string headers = "Content-Type: application/json\r\n";
   char post[]; StringToCharArray(payload, post, 0, StringLen(payload));
   char result[];
   string result_headers;

   ResetLastError();
   int res = WebRequest("POST", InpJournalApiUrl, headers, 5000, post, result, result_headers);

   if(res == -1)
     {
      int err = GetLastError();
      Print("JournalBridge: WebRequest failed, error ", err,
            ". Add the journal API domain to Tools > Options > Expert Advisors > Allow WebRequest.");
      return;
     }

   g_lastSync = TimeCurrent();
   Print("JournalBridge: sync OK, HTTP ", res, " at ", TimeToString(g_lastSync));
  }
